### ISSUE TITLE
add logging

### ISSUE THREAD

**Issue by AlexPoulsen** [flutterflies/schwarznasenschaf#3]
**Channel: log-membership**
- [x] member joins
- [x] member banned
- [x] member unbanned
- [ ] member kicked
- [ ] member rejoins after being kicked or unbanned
- [ ] member changes username or nickname
- [ ] strike or some other way of keeping track of rule breaking is added to a user
- [ ] strike removed

**Channel: log-messages**
- [ ] message edited
- [ ] message deleted
- [ ] bulk message delete
- [ ] bulk message move (with bot command)
- [ ] invite link posted

**Channel: log-roles**
- [ ] roles edited
- [ ] roles deleted
- [ ] roles added
- [ ] roles given to member

**Channel: log-channels**
- [ ] channel created
- [ ] channel topic edited
- [ ] channel deleted
- [ ] channel moved
- [ ] channel permission change
- [ ] category created
- [ ] category moved
- [ ] category permission change

**Comment by Not-Super-Nova** [comment]
I'm currently playing about with the code to add this, do you want it on a database that you can query with commands or just to dump to a logging channel?
Other answers ***are*** valid, that's just the two I came up with!

**Comment by flutterflies** [comment]
@Not-Super-Nova each of the 4 group of items should log to their own channel

**Comment by Not-Super-Nova** [comment]
Oooooh I see it now. That'll make it easier!

**Comment by Not-Super-Nova** [comment]
sorry, things have cropped up and i'll have to postpone working on this for a while.

**Comment by flutterflies** [comment]
### Membership logging

* member joins - in progress (doing leaves too)
* member banned - in progress
* member unbanned - in progress
* member kicked - I don't believe this is possible because I can't find evidence that Discord sends an event for this
* member rejoins after being kicked or unbanned - This is possible in the future for bans if we start keeping track of bans ourselves. Would not be possible for kicks because of the reason in the above bullet
* member changes username or nickname - not realistically possible for us at this time
* strike or some other way of keeping track of rule breaking is added to a user - this *might* be something we look into in the future 
* strike removed - same as above

Additionally I'm adding logging for when a member gets verified.
